### ISSUE TITLE
Clicked on the icon at fairshake.cloud, clicked on evaluate, received evaluations form for L1000CDS2 

### ISSUE THREAD

**Issue by AviMaayan** [Nitrogen-DCPPC/FAIRShake-chrome-extension#3]

**Comment by AviMaayan** [comment]
This happens for all sites without data, but in FAIRshake.cloud you also receive an insignia, for other sites the insignia is gray as desired.

**Comment by u8sand** [comment]
This isn't really a chrome extension bug but an open issue in FAIRshake--that-is the assessment form needs to handle assessment requests better.

https://github.com/Nitrogen-DCPPC/FAIRshake/issues/46

**Comment by u8sand** [comment]
Fixed in https://github.com/Nitrogen-DCPPC/FAIRshake/commit/3bd21638ce1f95d8c2ef45a967e2671478824a07
